### ISSUE TITLE
error using cjson module in V 0.1.29

### ISSUE THREAD

**Issue by jojo05** [lydiandy/cjson#2]
Hi, I installed your module and run the example with v0.1.29 and get this. Can you fix? Thanks

/root/.vmodules/lydiandy/cjson/cjson.v:107:17: warning: function `C.strlen` must be called from an `unsafe` block
  105 | pub fn get_string_value(obj &C.cJSON) string {
  106 |     s:=C.cJSON_GetStringValue(obj)
  107 |     return tos(s,C.strlen(s))
      |                    ~~~~~~~~~
  108 | }
  109 |
/root/.vmodules/lydiandy/cjson/cjson.v:121:18: warning: function `C.strlen` must be called from an `unsafe` block
  119 | pub fn json_print(json &C.cJSON) string {
  120 |     s := C.cJSON_Print(json)
  121 |     return tos(s, C.strlen(s))
      |                     ~~~~~~~~~
  122 | }
  123 |
/root/.vmodules/lydiandy/cjson/cjson.v:166:9: error: unknown function: cJSON_IsNull
  164 | pub fn (obj &C.cJSON) is_null(item string) bool {
  165 |     value := obj.get(item)
  166 |     return cJSON_IsNull(value)
      |            ~~~~~~~~~~~~~~~~~~~
  167 | }

**Comment by lydiandy** [comment]
already update to V0.2
